name: Renode linux tester
inputs:
  shared-dir:
    description: Path to shared directory
    required: true
  renode-run:
    description: Command or a list of commands to run in Renode
    required: true
  devices:
    description: Devices to set up
    required: false
    default: ""
  image-path:
    description: Compiled linux kernel path
    required: false
    default: "https://github.com/antmicro-labs/renode-linux-runner-action/releases/download/latest/images.tar.xz"
runs:
  using: composite
  steps:

    - id: important-checks
      run: |
        ls -alh
        ip addr
        pwd
      shell: bash

    - id: install-pip-packages
      run: pip3 install pexpect
      shell: bash

    - id: download-renode
      run: |
        wget https://github.com/renode/renode/releases/download/v1.13.0/renode_1.13.0_amd64.deb &&
        DEBIAN_FRONTEND=noninteractive sudo apt-get -y install --no-install-recommends \
        ./renode_1.13.0_amd64.deb
      shell: bash

    - id: get-images
      run: wget ${{ inputs.image-path }} && tar xvf images.tar.xz
      shell: bash
    
    - id: copy-user-path
      run: |
        sudo mkdir -p /mnt/user && \
        sudo cp -r "$(pwd)"/${{ inputs.shared-dir }} /mnt/user
      shell: bash

    - id: test
      run: sudo bash action/config "${{ inputs.renode-run }}" "${{ inputs.devices }}"
      shell: bash
