name: Build and test
on: [push, workflow_dispatch, repository_dispatch]

jobs:

  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      build: ${{ steps.filter.outputs.build }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          base: HEAD
          filters: |
            build:
              - 'br2-external/**'
  build:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.build == 'true' && !github.event.eee }}
    steps:
      - uses: actions/checkout@v3
      - name: install-buildroot
        run: git clone --branch 2022.11.2 https://github.com/buildroot/buildroot buildroot
      - name: build-kernel
        run: |
          cd buildroot && \
          make BR2_EXTERNAL=../br2-external hifive_unleashed_defconfig && \
          make -j4 && \
          cd .. && \
          mkdir images && \
          for i in hifive-unleashed-a00.dtb fw_payload.elf Image rootfs.cpio; do cp buildroot/output/images/$i images; done
      - name: compress
        run: tar cJvf images.tar.xz images
      - name: send-to-releases
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ github.token }}"
          automatic_release_tag: "latest"
          title: images
          files: |
            images.tar.xz
  default-configuration-test:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ !failure() }}
    steps:
      - uses: actions/checkout@v3

      - run: git clone https://github.com/antmicro/pyrav4l2.git tests/pyrav4l2

      - name: get packages
        if: ${{ env.ACT }}
        run: |
         sudo apt update -qq && sudo DEBIAN_FRONTEND=noninteractive apt-get -y install --no-install-recommends \
         python3-pip telnet iptables iproute2

      - name: run-in-renode
        uses: ./
        with:
          shared-dir: ./tests
          image-path: https://github.com/${{ github.repository }}/releases/download/latest/images.tar.xz
          renode-run: |
            ping -c 3 172.16.0.1
            wget example.org
            gpiodetect
            sh gpio.sh
            sh i2c.sh
            python test.py
            pip install ./pyrav4l2
            python controls-enumeration.py
          devices: |
            vivid
            gpio 0 16
            i2c 0x1C
