name: Build and test on pull request
on: [pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: get packages
        if: ${{ env.ACT }}
        run: |
         sudo apt update -qq && sudo DEBIAN_FRONTEND=noninteractive apt-get -y install --no-install-recommends \
         python3-pip telnet iptables iproute2 bc cpio rsync

      - name: build kernel
        run: ./scripts/compile.sh

      - run: git clone https://github.com/antmicro/pyrav4l2.git tests/pyrav4l2

      - name: test
        uses: ./
        with:
          shared-dir: ./tests
          image: ./images.tar.xz
          renode-run: |
            ping -c 3 172.16.0.1
            wget example.org
            gpiodetect
            sh gpio.sh
            sh i2c.sh
            python test.py
            pip install ./pyrav4l2
            python controls-enumeration.py
          devices: |
            vivid
            gpio 0 16
            i2c 0x1C
